services:
  app:
    container_name: mephi-lab-db
    restart: no
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DSN: "host=db user=kirill password=password dbname=myDB port=5432 sslmode=disable TimeZone=Europe/Moscow"

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: "myDB"
      POSTGRES_USER: "kirill"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: sample@localhost.ru
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: /dev/null
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80

volumes:
  pgadmin:
